#!/usr/bin/env python3
import subprocess

def main():
    env_vars = []
    with open('local.env', 'r') as fin:
        for line in fin.read().split('\n'):
            if line.strip() == '':
                continue
            i = line.find('=')
            env_vars.append({
                "key": line[:i],
                "value": line[i+1:],
            })

    with open('template.yaml','r') as fin:
        contents = fin.read()
        for var in env_vars:
            contents = contents.replace(f'[[{var["key"]}]]', var['value'])
        with open('template.sensitive.yaml','w') as fout:
            fout.write(contents)

    buildprocess = subprocess.run(['sam','build','-m', 'requirements.txt', '-t', 'template.sensitive.yaml'])
    if buildprocess.returncode != 0:
        raise Exception(f'Build failed {buildprocess}')
    subprocess.run(['sam','deploy','-t', 'template.sensitive.yaml'])

main()
