AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  classifier

  Sample SAM Template for classifier

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  ClassifierFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: lambda_classify.lambda_handler
      Runtime: python3.7
      Policies: 
        S3ReadPolicy:
          BucketName: [[BUCKET_ID]]
      Events:
        Classifier:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /classify
            Method: post
      Environment:
        Variables:
          BUCKET_ID: [[BUCKET_ID]]
          IN_AWS_LAMBDA: 'true'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClassifierApi:
    Description: "API Gateway endpoint URL for Prod stage for Classifier function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classify/"
  ClassifierFunction:
    Description: "Classifier Lambda Function ARN"
    Value: !GetAtt ClassifierFunction.Arn
  ClassifierFunctionIamRole:
    Description: "Implicit IAM Role created for Classifier function"
    Value: !GetAtt ClassifierFunctionRole.Arn
