#!/usr/bin/env python
import argparse
import sys
from analyze import analyze
from custom import do_custom


def run_analyze(sysargv: str):
    parser = argparse.ArgumentParser(description='Run entire analysis')
    parser.add_argument("-s", "--summary", action="store_true",
                        help="Print summary analysis only")
    parser.add_argument("-m", "--monthly", action="store_true",
                        help="Print monthly analysis only")
    parser.add_argument("-c", "--cutoff", type=int, default=12,
                        help="Specify how many months back to perform analysis")
    parser.add_argument("-e", "--spreadsheet",
                        action="store_true", help="Output a spreadsheet file")

    args = parser.parse_args(sysargv)
    if args.summary and args.monthly:
        print("--summary and --monthly cannot be present at the same time")
        exit(1)

    analyze(summaryonly=args.summary, monthlyonly=args.monthly,
            cutoffmonths=int(args.cutoff), spreadsheetout=args.spreadsheet)


def run_custom(sysargv: str):
    parser = argparse.ArgumentParser(description='Run custom thing', usage='')
    parser.add_argument("-c", "--cutoff", type=int, default=12,
                        help="Specify how many months back to perform analysis")
    args = parser.parse_args(sysargv)
    do_custom(int(args.cutoff))


parser = argparse.ArgumentParser(description='run finance analysis', usage='''

    Commands available:
        analyze     Run financial analysis
        custom      Run custom stuff
        test        Run test code
''')

commands = {
    "analyze": run_analyze,
    "custom": run_custom,
}

parser.add_argument("command", help="Subcommand to run")

# parse_args defaults to [1:] for args, but you need to
# exclude the rest of the args too, or validation will fail
args = parser.parse_args(sys.argv[1:2])
if not args.command in commands:
    print('Unrecognized command')
    parser.print_help()
    exit(1)

# use dispatch pattern to invoke method with same name
commands[args.command](sys.argv[2:])
